//
//  Test.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Test: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _name: String?
    var _nickname: String?
    
    class func dynamoDBTableName() -> String {

        return "airsplit-mobilehub-2093393909-test"
    }
    
    class func hashKeyAttribute() -> String {

        return "_name"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_nickname"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_name" : "name",
               "_nickname" : "nickname",
        ]
    }
}
